CREATE DATABASE PHOTOSYSTEM;
USE PHOTOSYSTEM;
CREATE TABLE USERS (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    JOINDATE DATE DEFAULT (CURRENT_DATE),
    PRIMARY KEY(USER_ID)
);
CREATE TABLE ALBUMS (
    ALBUM_ID INT NOT NULL AUTO_INCREMENT,
    ALBUMTITLE VARCHAR(100) NOT NULL,
    CREATED_AT DATE DEFAULT (CURRENT_DATE),
    USER_ID INT,
    PRIMARY KEY(ALBUM_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);
CREATE TABLE PHOTOS (
    PHOTO_ID INT NOT NULL AUTO_INCREMENT,
    FILENAME VARCHAR(255) NOT NULL,
    CAPTION VARCHAR(200),
    ALBUM_ID INT,
    PRIMARY KEY(PHOTO_ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMS(ALBUM_ID) ON DELETE CASCADE
);
CREATE TABLE DETAILS (
    DETAILS_ID INT NOT NULL AUTO_INCREMENT,
    CAMERA_MODEL VARCHAR(100),
    RESOLUTION VARCHAR(20),
    SIZE INT,
    PHOTO_ID INT,
    PRIMARY KEY(DETAILS_ID),
    FOREIGN KEY (PHOTO_ID) REFERENCES PHOTOS(PHOTO_ID) ON DELETE CASCADE
);
INSERT INTO USERS (USERNAME, EMAIL) VALUES ('초기값', 'initial@example.com');